version = 0.1
[default.deploy.parameters]
stack_name = "collect-whats-new"
resolve_s3 = true
s3_prefix = "collect-whats-new"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
