Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: python3.11
    Timeout: 360
    Handler: collectWhatsNew.handler
    Tracing: Active

Resources:
  CollectWhatsNewFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures: ["arm64"]
      FunctionName: CollectWhatsNew
      Policies:
        - S3ReadPolicy:
            BucketName: "*"
        - S3WritePolicy:
            BucketName: "aws-whats-new*"
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
              Resource: "*"
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(1 day)"
            FlexibleTimeWindow:
              Mode: FLEXIBLE
              MaximumWindowInMinutes: 10